config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'main#show', as: :root

  resources :posts do
    get :follow, on: :member
    get :unfollow, on: :member
    get :resolved, on: :member
  end

  resources :comments, only: [:create] do
    get :rate_up, on: :member
    get :rate_down, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :rates
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :user_posts
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :user_posts
  has_many :comments
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find_by!(id: comment_params[:post_id])

    current_user.comments.create(comment_params)

    post.update(updated_at: Time.now)

    redirect_to post_path(post)
  end

  def rate_up
    comment = Comment.find_by!(id: params[:id])
    comment.rates.create(user: current_user, value: true)
    redirect_to post_path(comment.post_id)
  end

  def reate_down
    comment = Comment.find_by!(id: params[:id])
    comment.rates.create(user: current_user, value: false)
    redirect_to post_path(comment.post_id)
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(:post_id, :text)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def show
    @posts = Post.joins(:user_posts)
                  .where(user_posts: { user_id: current_user.id })
                  .order(updated_at: :desc)

    redirect_to posts_path if @posts.none?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc).all
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)

    current_user.user_posts.create(post: @post)

    redirect_to post_path(@post)
  rescue => error
    flash.now[:error] = error.message
    render :new
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])

    @post.update(post_params)

    redirect_to post_path(@post)
  rescue => error
    flash.now[:error] = error.message
    render :edit
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def follow
    @post = Post.find_by(id: params[:id])

    current_user.user_posts.where(post: @post).first_or_create

    redirect_to post_path(@post)
  end

  def unfollow
    @post = Post.find_by(id: params[:id])

    current_user.user_posts.where(post: @post).delete_all

    redirect_to post_path(@post)
  end

  def resolved
    @post = current_user.posts.find_by(id: params[:id])

    @post.update({:resolved => true})

    redirect_to post_path(@post)
  end

  def new; end

  private

  def post_params
    params
      .require(:post)
      .permit(:header, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_new.html.erb
<div class="comment">
  <div class="form">
    <hr>
    <%= form_for @post.comments.new do |f| %>
      <span><%= I18n.t('posts.fields.body') %></span>
      <br>
      <%= f.text_area :text, size: "60x12" %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <br>
      <%= f.submit I18n.t('posts.submit') %>
    <% end %>
  </div>
</div>

app/views/comments/_show.html.erb
<li>
  <dt>
    <% can_rate = comment.user_id != current_user.id && !comment.rates.find { |rate| rate.user_id == current_user.id } %>
    <% if can_rate %>
      <%= link_to '+', rate_up_comment_path(comment) %>
    <% end %>
    <%= comment.rates.sum { |r| r.value ? 1 : -1 } %>
    <% if can_rate %>
        <%= link_to '-', rate_down_comment_path(comment) %>
    <% end %>
  </dt>
  <dd>
    <%= comment.text %>
  </dd>
</li>

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}/
    %title= 'Engineering.ai challenge'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %header
      .d-flex.flex-column.flex-md-row.align-items-center.p-1.px-md-4.mb-3.bg-white.border-bottom.shadow-sm
        %h5.my-0.mr-md-auto.font-weight-normal= link_to 'Q L Application', root_path
        %nav.my-2.my-md-0.mr-md-3
          %a.p-2.text-primary= link_to(I18n.t('posts.title'), posts_path)

        - if signed_in?
          %span.m-2= "#{current_user.email}"
          = link_to t('common.sign_out'), destroy_user_session_path, method: :delete, class: 'm-2 btn btn-danger'
        - else
          = link_to t('common.sign_in'), user_session_path, class: 'm-1 btn btn-outline-primary'
          = link_to t('common.sign_up'), new_user_registration_path, class: 'm-2 btn-outline-success'
    %main.container{role: 'main'}
      .px-5.py-2
        = yield

app/views/main/show.html.erb
<div class="list">
  <dl>
    <% @posts.each do |post| %>
      <%= render 'posts/post_item', post: post %>
    <% end %>
  </dl>
</div>

app/views/posts/_form.html.erb
<%= form_for post do |p| %>
  <span><%= I18n.t('posts.fields.header') %></span>
  <br>
  <%= p.text_field :header, size: "70" %>
  <br>
  <span><%= I18n.t('posts.fields.body') %></span>
  <br>
  <%= p.text_area :body, size: "40x12" %>
  <br>
  <%= p.submit I18n.t('posts.submit') %>
<% end %>

app/views/posts/_post_item.erb
<div style="width:100%; height:auto; border:1px solid #000000; margin: 5px">
  <text>
    <%= post.header%>
  </text>
  <div align="right">
    <%= link_to(I18n.t('posts.view'), post_path(post)) %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="post">
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="top tar">
  <%= button_to(I18n.t('posts.new'), new_post_path,  {method: :get, form_class: 'form', class: 'btn btn-small'}) %>
</div>

<div class="list">
  <dl>
    <% @posts.each do |post| %>
        <%= render 'posts/post_item', post: post %>
    <% end %>
  </dl>
</div>

app/views/posts/new.html.erb
<div class="post">
  <%= render 'form', post: current_user.posts.new %>
</div>

app/views/posts/show.html.erb
<div class="top tar">
  <%= link_to(I18n.t('common.back'), posts_path, {:style=>'border:1px solid #FF0000; margin:3px; color:#FF0000'}) %>
  <% if @post.resolved == false%>
    <% if current_user.id == @post.user_id %>
      <%= link_to(I18n.t('posts.edit'), edit_post_path(@post), {:style=>'border:1px solid #FF0000; margin:3px; color:#FF0000'}) %>
      <%= link_to(I18n.t('posts.resolve'), resolved_post_path(@post), {:style=>'border:1px solid #FF0000; margin:3px; color:#FF0000'}) %>
    <% end %>
    <% if current_user.user_posts.where(post: @post).exists? %>
        <%= link_to(I18n.t('posts.unfollow'), unfollow_post_path(@post), {:style=>'border:1px solid #FF0000; margin:3px; color:#FF0000'}) %>
    <% else %>
        <%= link_to(I18n.t('posts.follow'), follow_post_path(@post), {:style=>'border:1px solid #FF0000; margin:3px; color:#FF0000'}) %>
    <% end %>
  <% end %>
</div>

<div class="list">
  <div class="details">
    <h3><%= @post.header %></h3>
    <hr>
    <p><%= @post.body %></p>
    <hr>
  </div>
  <div class="comments">
    <div class="list">
      <dl>
        <% @post.comments.preload(:rates).each do |comment| %>
          <%= render 'comments/show', comment: comment %>
        <% end %>
      </dl>
    </div>
  </div>
</div>

<% unless current_user.id == @post.user_id %>
  <%= render 'comments/new' %>
<% end %>